# libs/opmp_services/opmp_kernel/phase4_response_generation.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Phase 4: Response Generation with Progressive Markdown Streaming

This module implements token-by-token markdown streaming using LangChain
streaming callbacks for ChatGPT-style progressive rendering.

Author: Claude (SuperClaude)
Date: 2025-10-01
"""

import asyncio
import json
import logging
from typing import Dict, Any, AsyncGenerator, List, Optional
from config import SYSTEM_DEFAULT_LANGUAGE
from libs.utils.language import build_language_instruction, normalize_language
from langchain.callbacks.base import AsyncCallbackHandler

logger = logging.getLogger(__name__)


# Prompt template for Phase 4 (language instruction is injected dynamically)
RESPONSE_GENERATION_PROMPT = """你是一個專業的筆記型電腦銷售助手。請根據以下產品資料回答用戶的問題。

用戶查詢：{user_query}

查詢分析：
- 意圖：{intent}
- 關注重點：{user_focus}

產品資料：
{product_context}

{language_instruction}
格式要求：
1. 使用 Markdown 格式（headers, bold, tables）
2. 如果是產品比較，使用表格呈現關鍵規格差異
3. 提供清晰的購買建議，說明適用場景
4. 保持專業但友善的語氣

開始回答：
"""


class ProgressiveStreamingCallback(AsyncCallbackHandler):
    """
    Custom LangChain callback for progressive markdown streaming

    This callback captures tokens as they are generated by the LLM
    and sends them through a queue for streaming to the client.

    Features:
    - Token-by-token streaming
    - Async-safe queue communication
    - Error handling and completion signaling
    """

    def __init__(self, queue: asyncio.Queue):
        """
        Initialize callback

        Args:
            queue: Async queue for token streaming
        """
        self.queue = queue
        self.accumulated_text = ""

    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Called when LLM generates a new token

        Args:
            token: Generated token string
        """
        self.accumulated_text += token
        await self.queue.put({
            "type": "markdown_token",
            "token": token,
            "phase": 4
        })

    async def on_llm_end(self, response, **kwargs) -> None:
        """Called when LLM generation completes"""
        logger.info(f"LLM generation completed ({len(self.accumulated_text)} chars)")

    async def on_llm_error(self, error: Exception, **kwargs) -> None:
        """Called when LLM encounters an error"""
        logger.error(f"LLM generation error: {error}")
        await self.queue.put({
            "type": "error",
            "message": str(error),
            "phase": 4
        })


class Phase4ResponseGeneration:
    """
    Phase 4: Response Generation with Progressive Markdown Streaming

    This class generates LLM responses with token-by-token streaming
    for real-time markdown rendering in the frontend.

    Features:
    - Progressive markdown streaming
    - LangChain streaming callbacks
    - Context formatting
    - Response caching (optional)
    - Temperature optimization
    """

    def __init__(self, llm: Any, cache: Optional[Any] = None):
        """
        Initialize Phase 4 processor

        Args:
            llm: LangChain LLM instance (must support streaming)
            cache: Optional cache instance for response caching
        """
        self.llm = llm
        self.cache = cache

        # Configure LLM for streaming if possible
        if hasattr(self.llm, 'streaming'):
            self.llm.streaming = True

        # Set lower temperature for more deterministic responses
        if hasattr(self.llm, 'temperature'):
            self.llm.temperature = 0.3

        logger.info("Phase4ResponseGeneration initialized with streaming")

    async def process(
        self,
        query: str,
        analysis: Dict[str, Any],
        context: Dict[str, Any]
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """
        Generate response with progressive streaming

        Args:
            query: User query
            analysis: Query analysis from Phase 1
            context: Context from Phase 3

        Yields:
            Progress updates and markdown tokens
        """
        try:
            yield {
                "type": "progress",
                "phase": 4,
                "message": "Processing data output...", #"正在進行資料輸出處理...",
                "progress": 75
            }

            # Check cache first (optional)
            if self.cache:
                cached = await self._get_cached_response(query, context)
                if cached:
                    logger.info("Phase 4 cache hit")
                    # Stream cached response token by token for consistent UX
                    for token in cached:
                        yield {
                            "type": "markdown_token",
                            "token": token,
                            "phase": 4,
                            "from_cache": True
                        }

                    yield {
                        "type": "progress",
                        "phase": 4,
                        "message": "✅ Answer generation completed (from cache)", #"✅ 回答生成完成（從緩存）",
                        "progress": 95
                    }
                    return

            # Prepare prompt with language instruction
            lang_from_ctx = (analysis or {}).get("language") or (context or {}).get("language")
            language_instruction = build_language_instruction(lang_from_ctx or SYSTEM_DEFAULT_LANGUAGE)
            prompt = self._build_prompt(query, analysis, context, language_instruction)

            # Setup streaming queue for token-by-token delivery
            queue = asyncio.Queue()

            # Start LLM generation in background task
            async def generate():
                try:
                    full_response = ""

                    # OllamaLLM doesn't support callbacks, use native streaming
                    if hasattr(self.llm, 'astream'):
                        # Use async streaming (preferred)
                        async for chunk in self.llm.astream(prompt):
                            token = str(chunk) if chunk else ""
                            if token:
                                full_response += token
                                await queue.put({
                                    "type": "markdown_token",
                                    "token": token
                                })
                    elif hasattr(self.llm, 'ainvoke'):
                        # Async invoke without streaming
                        response = await self.llm.ainvoke(prompt)
                        full_response = str(response) if response else ""
                        # Simulate streaming by chunking response
                        chunk_size = 10
                        for i in range(0, len(full_response), chunk_size):
                            chunk = full_response[i:i+chunk_size]
                            await queue.put({
                                "type": "markdown_token",
                                "token": chunk
                            })
                            await asyncio.sleep(0.01)  # Small delay for streaming effect
                    else:
                        # Fallback to sync invoke
                        response = await asyncio.to_thread(self.llm.invoke, prompt)
                        full_response = str(response) if response else ""
                        # Simulate streaming by chunking response
                        chunk_size = 10
                        for i in range(0, len(full_response), chunk_size):
                            chunk = full_response[i:i+chunk_size]
                            await queue.put({
                                "type": "markdown_token",
                                "token": chunk
                            })
                            await asyncio.sleep(0.01)  # Small delay for streaming effect

                    await queue.put(None)  # Signal completion
                except Exception as e:
                    logger.error(f"LLM generation error: {e}")
                    await queue.put({
                        "type": "error",
                        "message": str(e)
                    })
                    await queue.put(None)

            task = asyncio.create_task(generate())

            # Stream tokens as they arrive
            full_response = ""
            while True:
                token_data = await queue.get()

                if token_data is None:
                    break

                if token_data.get("type") == "markdown_token":
                    full_response += token_data["token"]

                yield token_data

            await task

            # Cache response if enabled
            if self.cache and full_response:
                await self._cache_response(query, context, full_response)

            yield {
                "type": "progress",
                "phase": 4,
                "message": "✅ Answer generation completed", #"✅ 回答生成完成",
                "progress": 95
            }

        except Exception as e:
            logger.error(f"Phase 4 error: {e}")
            yield {
                "type": "error",
                "message": f"Answer generation failed: {str(e)}", #f"回答生成失敗: {str(e)}",
                "phase": 4
            }

    def _build_prompt(
        self,
        query: str,
        analysis: Dict[str, Any],
        context: Dict[str, Any],
        language_instruction: str
    ) -> str:
        """
        Build prompt for LLM

        Args:
            query: User query
            analysis: Query analysis
            context: Product context

        Returns:
            Complete prompt string
        """
        # Format product context
        product_context = self._format_product_context(context["products"])

        # Build prompt from template
        prompt = RESPONSE_GENERATION_PROMPT.format(
            user_query=query,
            intent=analysis.get("intent", "general"),
            user_focus=analysis.get("user_focus", "全面評估"),
            product_context=product_context,
            language_instruction=language_instruction
        )

        return prompt

    def _format_product_context(self, products: List[Dict[str, Any]]) -> str:
        """
        Format product data for LLM context

        Args:
            products: List of product dictionaries

        Returns:
            Formatted context string
        """
        if not products:
            return "(No related product data)" #"（無相關產品資料）"

        context_parts = []

        for idx, product in enumerate(products, 1):
            product_text = f"\n### Product {idx}: {product.get('modelname', 'Unknown')}\n"
            product_text += f"- 型號: {product.get('modeltype', 'N/A')}\n"

            # Core specs
            if product.get('cpu'):
                product_text += f"- CPU: {product['cpu']}\n"
            if product.get('gpu'):
                product_text += f"- GPU: {product['gpu']}\n"
            if product.get('memory'):
                product_text += f"- Memory: {product['memory']}\n"
            if product.get('storage'):
                product_text += f"- Storage: {product['storage']}\n"
            if product.get('lcd'):
                product_text += f"- LCD: {product['lcd']}\n"
            if product.get('battery'):
                product_text += f"- Battery: {product['battery']}\n"

            # Additional features if available
            if product.get('thermal'):
                product_text += f"- Thermal: {product['thermal']}\n"
            if product.get('ai'):
                product_text += f"- AI Function: {product['ai']}\n"

            # Semantic context
            if product.get('semantic_content'):
                product_text += f"\nRelated information: {product['semantic_content']}\n"

            context_parts.append(product_text)

        return "\n".join(context_parts)

    async def _get_cached_response(
        self,
        query: str,
        context: Dict[str, Any]
    ) -> Optional[str]:
        """Get cached response"""
        if not self.cache:
            return None

        try:
            import hashlib

            # Create cache key from query + product IDs
            product_ids = [p.get("modeltype", "") for p in context["products"][:3]]
            cache_input = f"{query}:{':'.join(product_ids)}"
            query_hash = hashlib.md5(cache_input.encode()).hexdigest()
            cache_key = f"phase4:{query_hash}"

            cached = await self.cache.get_async(cache_key)
            if cached:
                return cached

        except Exception as e:
            logger.warning(f"Cache get error: {e}")

        return None

    async def _cache_response(
        self,
        query: str,
        context: Dict[str, Any],
        response: str
    ) -> None:
        """Cache response"""
        if not self.cache:
            return

        try:
            import hashlib

            # Create cache key from query + product IDs
            product_ids = [p.get("modeltype", "") for p in context["products"][:3]]
            cache_input = f"{query}:{':'.join(product_ids)}"
            query_hash = hashlib.md5(cache_input.encode()).hexdigest()
            cache_key = f"phase4:{query_hash}"

            await self.cache.set_async(
                cache_key,
                response,
                ttl=1800  # 30 minutes
            )

        except Exception as e:
            logger.warning(f"Cache set error: {e}")
